package io.ezz.launcher.core.model.instance

import kotlinx.serialization.Serializable

/**
 * Action type for each item in an InstallationPlan.
 */
@Serializable
enum class PlanActionType {
    KEEP,
    INSTALL,
    UPDATE,
    REPLACE,
    REMOVE
}

/**
 * An individual item in an InstallationPlan representing an existing or candidate mod.
 */
@Serializable
data class PlanItem(
    val action: PlanActionType,
    val modId: String,
    val modName: String,
    val currentVersion: String? = null,
    val targetVersion: String? = null,
    val fileName: String,
    val downloadUrl: String? = null,
    val fileSize: Long = 0L,
    val isPrimary: Boolean = false,
    val reason: String = "",
    val causedByConstraint: String? = null,
    val metadata: Map<String, String> = emptyMap()
)

/**
 * Immutable and fully deterministic installation plan generated by the Global Dependency Solver.
 * Validates the exact set of mod files that should exist before and after the transaction.
 */
@Serializable
data class InstallationPlan(
    val environment: ResolvedEnvironment,
    val targetModId: String,
    val targetModName: String,
    val selectedVersionNumber: String,
    val items: List<PlanItem>,
    val initialModFileNames: Set<String>,
    val expectedFinalModFileNames: Set<String>
) {
    val itemsToInstall: List<PlanItem>
        get() = items.filter { it.action == PlanActionType.INSTALL }

    val itemsToKeep: List<PlanItem>
        get() = items.filter { it.action == PlanActionType.KEEP }

    val itemsToUpdate: List<PlanItem>
        get() = items.filter { it.action == PlanActionType.UPDATE }

    val itemsToReplace: List<PlanItem>
        get() = items.filter { it.action == PlanActionType.REPLACE }

    val itemsToRemove: List<PlanItem>
        get() = items.filter { it.action == PlanActionType.REMOVE }

    /**
     * Safety invariant: The plan must normally be purely additive with zero unexpected removals.
     */
    val isPureAdditive: Boolean
        get() = itemsToRemove.isEmpty() && itemsToReplace.isEmpty()
}
