name = "ezz-launcher-web"
main = "src/worker.js"
compatibility_date = "2026-08-26"
account_id = "f33e2302655eedc2f93ac28d25d9595b"
workers_dev = true

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[routes]]
pattern = "ezzlauncher.dpdns.org/*"
zone_id = "60f807a8b844cdae499f8f2718c0384f"

[[routes]]
pattern = "www.ezzlauncher.dpdns.org/*"
zone_id = "60f807a8b844cdae499f8f2718c0384f"
